# Generated by Django 4.1.4 on 2022-12-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_fruits'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fruits',
            index=models.Index(fields=['fruit_name'], name='document_fr_fruit_n_4228c5_idx'),
        ),
    ]
