# Generated by Django 4.1.4 on 2022-12-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_fruits_document_fr_fruit_n_4228c5_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('roll_number', models.IntegerField()),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
